<?xml version="1.0"?>
<package format="3">
  <name>hex_flow_ros_camera</name>
  <version>0.0.1</version>
  <description>HexFlow ROS2 camera nodes (USB, Dummy, RealSense, Berxel)</description>
  <maintainer email="thetaigon@qq.com">taigon</maintainer>
  <license>Apache-2.0</license>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>hex_flow_ros_common</exec_depend>
  <exec_depend>hex_flow_ros_msg</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
